default:
  DEBUG: True
  APPIUM_SERVER: "http://localhost:4723/wd/hub"

stage:
  DEBUG: True
  APPIUM_SERVER: "http://stage-address:4723/wd/hub"
  ANDROID:
    platformName: "Android"
    deviceName: "emulator"
    app: ""
    platformVersion: "15"
    automationName: "uiautomator2"

prod:
  DEBUG: True
  APPIUM_SERVER: "http://prod-adress:4723/wd/hub"
  IOS:
    platformName: "iOS"
    deviceName: "iPhone 14"
    bundleId: "com.example.app"
    automationName: "XCUITest"
