stage:
  DEBUG: True
  APPIUM_SERVER: "http://127.0.0.1:4723/wd/hub"
  ANDROID:
    platformName: "Android"
    deviceName: "emulator"
    platformVersion: "15"
    newCommandTimeout: 3000
    autoGrantPermissions: True
    appWaitForLaunch: True
    maxRetryCount: 40
    noReset: False
    appWaitDuration: 30000
    appPackage: "io.appium.android.apis"
    appActivity: "io.appium.android.apis.ApiDemos"
    automationName: "uiautomator2"

  IOS:
    platformName: "iOS"
    deviceName: "iPhone 14"
    bundleId: "ua.com.test.app"
    automationName: "XCUITest"

prod:
  DEBUG: True
  APPIUM_SERVER: "http://prod-adress:4723/wd/hub"
  IOS:
    platformName: "iOS"
    deviceName: "iPhone 14"
    bundleId: "com.example.app"
    automationName: "XCUITest"
